<?php

include '../conn.php';



$sql = "CREATE TABLE sem3(
	First_name VARCHAR(30) NOT NULL,
	Last_Name VARCHAR(30) NOT NULL,
	Jntu_No VARCHAR(30) NOT NULL,
	Year_of_Addmision INT(4) NOT NULL,
	Email_Id VARCHAR(30) NOT NULL,
	Mobile_No BIGINT(10) NOT NULL,
	Gender VARCHAR(10) NOT NULL,
	Semester INT(2) NOT NULL,
	CV_co1 INT(2) NOT NULL,CV_co2 INT(2) NOT NULL,CV_co3 INT(2) NOT NULL,CV_co4 INT(2) NOT NULL,CV_co5 INT(2) NOT NULL,CV_co6 INT(2) NOT NULL,
	DE_co1 INT(2) NOT NULL,DE_co2 INT(2) NOT NULL,DE_co3 INT(2) NOT NULL,DE_co4 INT(2) NOT NULL,DE_co5 INT(2) NOT NULL,DE_co6 INT(2) NOT NULL,
	EDC_co1 INT(2) NOT NULL,EDC_co2 INT(2) NOT NULL,EDC_co3 INT(2) NOT NULL,EDC_co4 INT(2) NOT NULL,EDC_co5 INT(2) NOT NULL,EDC_co6 INT(2) NOT NULL,
	LCA_co1 INT(2) NOT NULL,LCA_co2 INT(2) NOT NULL,LCA_co3 INT(2) NOT NULL,LCA_co4 INT(2) NOT NULL,LCA_co5 INT(2) NOT NULL,LCA_co6 INT(2) NOT NULL,
	RVSP_co1 INT(2) NOT NULL,RVSP_co2 INT(2) NOT NULL,RVSP_co3 INT(2) NOT NULL,RVSP_co4 INT(2) NOT NULL,RVSP_co5 INT(2) NOT NULL,RVSP_co6 INT(2) NOT NULL,
	SS_co1 INT(2) NOT NULL,SS_co2 INT(2) NOT NULL,SS_co3 INT(2) NOT NULL,SS_co4 INT(2) NOT NULL,SS_co5 INT(2) NOT NULL,SS_co6 INT(2) NOT NULL,
	DE_LAB_co1 INT(2) NOT NULL,DE_LAB_co2 INT(2) NOT NULL,DE_LAB_co3 INT(2) NOT NULL,DE_LAB_co4 INT(2) NOT NULL,DE_LAB_co5 INT(2) NOT NULL,DE_LAB_co6 INT(2) NOT NULL,
	EDC_LAB_co1 INT(2) NOT NULL,EDC_LAB_co2 INT(2) NOT NULL,EDC_LAB_co3 INT(2) NOT NULL,EDC_LAB_co4 INT(2) NOT NULL,EDC_LAB_co5 INT(2) NOT NULL,EDC_LAB_co6 INT(2) NOT NULL,
	SS_LAB_co1 INT(2) NOT NULL,SS_LAB_co2 INT(2) NOT NULL,SS_LAB_co3 INT(2) NOT NULL,SS_LAB_co4 INT(2) NOT NULL,SS_LAB_co5 INT(2) NOT NULL,SS_LAB_co6 INT(2) NOT NULL,
	IMAGE_LOCATION LONGTEXT NOT NULL
)";

$result = $conn->query($sql);

if ($result)
{
    echo "Table created successfully.";
}
else
{
    echo "ERROR: Could not able to execute $sql. " . mysqli_error($result);
}

?>
